# Overriding product variant resource
#sylius_product:
#  resources:
#    product_variant:
#      classes:
#        model: Gweb\SyliusProductDepositPlugin\Entity\ProductVariant

# New channel deposit resources
sylius_resource:
  resources:
    gweb_deposit.channel_deposit:
      classes:
        model: Gweb\SyliusProductDepositPlugin\Entity\ChannelDeposit
        interface: Gweb\SyliusProductDepositPlugin\Entity\ChannelDepositInterface
        form: Gweb\SyliusProductDepositPlugin\Form\ChannelDepositType
